// ui/src/components/tools/Bmi.jsx
import React, { useEffect, useState } from 'react'

export const Bmi = () => {
  const [weight, setWeight] = useLocalStorage('bmi:weight', 75)
  const [height, setHeight] = useLocalStorage('bmi:height', 185)

  const cHeight = (height / 100) ** 2
  const bmi = weight / cHeight

  const setBmi = value => {
    setWeight(value * cHeight)
  }

  return <>
    <h1>BMI Calculator</h1>

    <rdcl-input-grid>
      <label htmlFor="weight">Weight (in kgs)</label>
      <input
        id="weight"
        type="number"
        inputMode="decimal"
        step="any"
        value={ formatted(weight) }
        onChange={ event => setWeight(event.target.value) }
      />

      <label htmlFor="height">Height (in cms)</label>
      <input
        id="height"
        type="number"
        inputMode="decimal"
        step="any"
        value={ height }
        onChange={ event => setHeight(event.target.value) }
      />

      <label htmlFor="bmi">BMI</label>
      <input
        id="bmi"
        type="number"
        inputMode="decimal"
        step="any"
        value={ formatted(bmi) }
        onChange={ event => setBmi(event.target.value) }
      />
    </rdcl-input-grid>
  </>
}

function useLocalStorage(key, initial) {
  const getFromLocalStorage = () => localStorage[key] ? +localStorage[key] : initial
  const [value, setValue] = useState(getFromLocalStorage())

  useEffect(() => {
    const handler = (event) =>
      event.key === key && setValue(getFromLocalStorage())

    window.addEventListener('storage', handler)
    return () => {
      window.removeEventListener('storage', handler)
    }
  })

  return [
    value,
    newValue => {
      localStorage[key] = newValue
      setValue(+newValue)
    },
  ]
}

function formatted(value) {
  return value === 0 ? '' : Number(value.toFixed(2))
}

// apps/tools/src/views/BMI.vue
<template>
  <form>
    <p>
      <label for="weight">Weight (in kgs)</label><br>
      <input
          id="weight"
          type="number"
          inputmode="decimal"
          :value="formatted(weight)"
          @input="$event.target.value && weightUpdated(+$event.target.value)"
          @change="weightUpdated(+$event.target.value)"
          step="any"
      >
    </p>

    <p>
      <label for="height">Height (in cms)</label><br>
      <input
          id="height"
          type="number"
          inputmode="decimal"
          v-model.number="height"
          step="any"
      >
    </p>

    <p>
      <label for="bmi">BMI</label><br>
      <input
          id="bmi"
          type="number"
          inputmode="decimal"
          :value="formatted(bmi)"
          @input="$event.target.value && bmiUpdated(+$event.target.value)"
          @change="bmiUpdated(+$event.target.value)"
          step="any"
      >
    </p>
  </form>
</template>

<script lang="ts">
  import { Component, Vue, Watch } from 'vue-property-decorator'

  @Component
  export default class BMI extends Vue {
    weight: number
    height: number

    get bmi(): number {
      return this.weight / this.cHeight
    }

    constructor() {
      super();

      this.weight = readValue('bmi:weight', 75)
      this.height = readValue('bmi:height', 185)
    }

    @Watch('weight')
    private onWeightChanged(value: number) {
      writeValue('bmi:weight', value)
    }

    @Watch('height')
    private onHeightChanged(value: number) {
      writeValue('bmi:height', value)
    }

    weightUpdated(weight: number) {
      this.weight = weight
    }

    bmiUpdated(bmi: number) {
      this.weight = bmi * this.cHeight
    }

    formatted(value: number): number {
      return Number(value.toFixed(2))
    }

    private get cHeight(): number {
      return (this.height / 100) ** 2
    }
  }

  function readValue(key: string, dflt: number): number {
    const value = localStorage.getItem(key)

    return value ? +value : dflt
  }

  function writeValue(key: string, value: number) {
    localStorage.setItem(key, "" + value)
  }
</script>

<style scoped lang="sass">
</style>
