// src/pages/Auth/Login.tsx
import React, { useId } from 'react'
import { ActiveRoute } from '../../components/ActiveRoute'
import { Title } from '../../components/Title'
import { useLogin } from './hooks'

export const Login = () => {
  const id = useId()
  const { state, register, handleSubmit } = useLogin()

  return (
    <>
      <Title>log in</Title>
      <ActiveRoute />
      <h1>Log in</h1>

      {state === 'success' ? (
        <p>Login request sent successfully, please wait for an e-mail.</p>
      ) : (
        <form onSubmit={handleSubmit}>
          <rdcl-input-grid>
            <label htmlFor={id}>User</label>
            <input
              id={id}
              type="text"
              autoCapitalize="off"
              disabled={state === 'pending'}
              required
              {...register('username', {
                required: true,
              })}
            />

            <button data-start={2} disabled={state === 'pending'}>
              Log in
            </button>

            <label data-start={2}>
              <input
                type="checkbox"
                disabled={state === 'pending'}
                {...register('rememberMe')}
              />{' '}
              Remember me
            </label>

            {state === 'error' && (
              <p className="error-message" data-start={2}>
                Unable to send the login request.
              </p>
            )}
          </rdcl-input-grid>
        </form>
      )}
    </>
  )
}
export default Login

// app/src/routes/login/+page.svelte
<script lang="ts">
  import type { ActionData } from './$types'

  export let form: ActionData
</script>

<svelte:head>
  <title>log in | rdcl.dev</title>
</svelte:head>

<h1>Log in</h1>
{#if form?.success}
  <p>Login request sent successfully, please wait for an e-mail.</p>
{:else}
  <form method="POST">
    <section class="form-grid">
      <label for="login:email">Username</label>
      <input
        id="login:email"
        name="email"
        type="text"
        autocomplete="username"
        required
      />
      <button data-start="2">Log in</button>
      {#if form?.errors}
        <p data-start="2" class="error">{form?.errors.join(', ')}</p>
      {/if}
    </section>
  </form>
{/if}

<style>
  form {
    max-inline-size: 35rem;
  }
</style>
